//> using scala "3.5.0"
//> using jar "lib/stainless-library.jar"
//> using jar "lib/stainless-library-sources.jar"
//> using dep "org.scalameta::munit::1.0.2"
//> using options "-Wconf:msg=not.*?exhaustive:s,msg=pattern.*?specialized:s"
